### PR TITLE
Added Death Counter

### PR DESCRIPTION
**Pull request by Kand1Kane**
DeathCounter are now added to every level and resets once you restart that respective level or going back to the main screen. Note that I kept the DeathCounter up when game is paused and when player wins the game.

In addition, the loading screen would have the DeathCounter appear on the top left. It's a feature, not a bug.

### CODE REVIEW

**Review by NoahFreelove — CHANGES_REQUESTED** [review]
Please change the text from "lives" to "deaths" if its a death counter. Also make it count upwards. A negative death counter is not very intuitive.

image

**Comment by Kand1Kane** [comment]
Hello, it's supposed to represent a live counter technically. The reason is I feel like showing the user a negative live counter would be taunting and annoying to the user which adds a comedic effect. I can either change the names of the code or keep the comedic design based on your thoughts.

**Comment by NoahFreelove** [comment]
I think the average user would perceive this as a bug not a feature, and it would add confusion to the overall game

**Comment by Kand1Kane** [comment]
I see, I was mostly inspired by how Mario would display the amount of lives you have left after you die and in cat Mario they utilized that and purposely made it so that if you die more than the original lives, the live counter goes negative. You can try it out here.

https://catmario.eu/

If you still think it's confusing we can change it! Thanks :)

**Comment by NoahFreelove** [comment]
Okay then, it makes sense to keep it negative but instead of using the text "Lives" instead I suggest use an image of the player maybe? I think that would convey the humor better.

**Comment by Kand1Kane** [comment]
I have now changed to the death counter since it was more intuitive.

**Review by NoahFreelove — COMMENTED** [review]
The changes work great and I think having it count upwards makes much more sense for our game. I approve of the merge

**Pull request merged**
